### ISSUE TITLE
USER STORY: Education on different gin types

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#1]
As a **customer**, I can **learn about the different types of gins there are**, so that **I can make famous gin cocktails with the right type of gin**.

### Acceptance Criteria
- List the different types of gin, but cap it at 10 to reduce user exhaustion
- An image of the type of gin should be displayed
- A description of what the type of gin is and it's role in the drink
- A link to buy the type of gin (onsite or externally)

### Tasks
- [x] Research the the best gins of each category. I.e. Best dry gin, best pink gin etc.
- [x] Write a description of the best ranked in gin in their respective category
- [x] Find out where customers can buy this gin, so they can purchase the bottles they would like
- [x] List the price of the bottle, but state that price can vary using an asterisk
- [x] Develop an iteration list to display the data, to reduce repetitive code

### Story Point Estimation
A score of 3 points

**Comment by LeanneCodes** [comment]
This is complete
