### ISSUE TITLE
USER STORY: Fun facts on gin

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#12]
As a **site owner**, I can **display all the fun facts about gin**, so that **visitors to the site are more intrigued about gin and willing to try a class**.

### Acceptance Criteria
- Ensure facts are correct
- Display a minimum of 10 facts along with imagery to make the page informative and appealing

### Tasks
- [x] Create a separate page on these facts
- [x] Utilise Bootstrap's grid layout to display the facts alongside images
- [x] Use Cloudinary to store all images

### Story Points Estimation
A score of 2 points

**Comment by LeanneCodes** [comment]
This is complete
