### ISSUE TITLE
USER STORY: A clear call to action on the homepage

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#2]
As a **customer**, I can **instantly know what the purpose of the website is**, so that **I can click on the relevant buttons/path, to get me to book a class**.

### Acceptance Criteria
- Homepage needs to have a clear call to action to guide users to book a class
- Homepage displays imagery and incentive to encourage users to book a class

### Tasks
- [x] Develop a homepage that has enticing imagery to encourage user participation
- [x] Show a range of customer reviews to encourage users to book a class
- [x] Develop a short path journey from homepage to booking a class

### Story Points Estimation
A score of 5 points

**Comment by LeanneCodes** [comment]
This is complete
