### ISSUE TITLE
USER STORY: Authenticated users

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#4]
As a **developer**, I can **limit access to certain pages**, so that **only logged in users can book a class and view their bookings**.

### Acceptance Criteria
- The call to action message must change depending on if a user is logged in or not
- The navigation links must update depend if a user is logged in or not
- Only logged in users can book a class and view it

### Tasks
- [x] Add an if statement to the navigation bar to determine what links will be displayed to the user depending if they are logged in or not
- [x] Add an if statement to the call-to-action buttons, so logged in users see "Book now" and non-logged in users see "Join Us"
- [x] Create a link specifically for logged in users to see their own bookings on a separate html page

### Story Points Estimation
A score of 5 points

Links to #8

**Comment by LeanneCodes** [comment]
This is complete.
