### ISSUE TITLE
USER STORY: Booking Form

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#5]
As a **customer**, I can **create a booking and choose which mixologist I want to be taught by**, so that **I can learn from their experience and someone who has similarities to myself**.

### Acceptance Criteria
- The booking form needs to include validation
- The booking form needs to ask for the basic requirements, such as name, email, date of booking and choice of mixologist at a minimum
- The form must be able to submit successfully
- The user is notified that their booking was successful or not

### Tasks
- [x] Create a booking form that has required fields the user must complete before their form can be submitted
- [x] Include the csrf token when building the form, to ensure user data is safe and prevent any unwanted issues, such as hacking
- [x] Redirect the user to a new page, where they view they have just created
- [x] Notify the user using alerts to show that their booking was either created successfully or not, if there is an error

### Story Points Estimation
A score of 3 points

 Links to #6

**Comment by LeanneCodes** [comment]
This is complete
