### ISSUE TITLE
USER STORY: Edit and delete bookings

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#6]
As a **customer**, I can **edit and delete my bookings**, so that **I can be in control of my bookings**.

### Acceptance Criteria
- A user must be able to see options to edit and delete bookings
- A user must be notified of the changes they make

### Tasks
- [x] Build to buttons that iterate for every item in the form list, so every booking has the option to edit or delete the booking
- [x] Direct the user to a separate page to update their booking and allow them to resubmit and be notified of this change
- [x] Allow the user to delete a booking with ease

### Story Points Estimation
A score of 5 points

**Comment by LeanneCodes** [comment]
This is complete
