### ISSUE TITLE
USER STORY: Send an email

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#7]
As a **customer**, I can **send an email to GinTopia**, so that **I can make sure they see any enquiries that I have**.

### Acceptance Criteria
- Email form must be short to encourage enquiries
- Email page must either notify or refresh to give an indication that an email has been sent successfully
- The page should include any additional information that can help reduce enquiry emails, such as location of the class

### Tasks
- [x] Create a simple email form that links to GinTopia's email team, so that they can respond to enquiries in a timely manner
- [x] Include the address of the venue 
- [x] Include a map of the venue, which uses a Google Map API, so users can navigate where they're going at ease

### Story Points Estimation
A score of 3 points

**Comment by LeanneCodes** [comment]
This is complete
