### ISSUE TITLE
USER STORY: Logging in and logging out must be a straightforward process

### ISSUE THREAD

**Issue by LeanneCodes** [LeanneCodes/GinTopia_NEW#8]
As a **developer**, I can **ensure the steps to log in and out are simple**, so that **users can create accounts and create bookings with ease**.

### Acceptance Criteria
- Short sign up form that only includes what is required from a user, such as username, email (optional) and password
- If the user has already created an account, they must be directed to another page that allows them to login
- If the user is logged in and wishes to log out, they can do so with ease

### Tasks
- [x] Use Django's framework to include templated sign up/login/logout html pages, which are designed to reduce manual code and creates simple forms that users can benefit from
- [x] Notify the user when they are logged in with an alert, so that it's clear to them on site
- [x] Notify the user when they log out with an alert, so that it's clear to them on site
- [x] Style the Django html template files so that it's in line with the website's theme and layout

### Story Points Estimation
A score of 1 point

**Comment by LeanneCodes** [comment]
This is complete
